# This config file is used when previewing the site with "rake preview"
# or "rake deploy-preview"
# The variables defined in this file will overwrite those in _config.yml

twitter_tweet_button: false

google_plus_one: false
googleplus_hidden: true

addthis_profile_id:

disqus_short_name:
disqus_show_comment_count: false

google_analytics_tracking_id:
google_analytics_domain_name:

facebook_like: false
